package com.ram.employee.dao.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.core.support.JdbcDaoSupport;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

import com.ram.employee.dao.EmployeeDAO;

public class EmployeeDAOImpl
		extends JdbcDaoSupport implements EmployeeDAO
{

	public void retriveAutoGeneratedKey()
	{
		final String INSERT_SQL = "INSERT INTO EMPLOYEE "
				+ "(NAME, AGE,SALARY) VALUES (?, ?, ?)";

		KeyHolder keyHolder = new GeneratedKeyHolder();
		getJdbcTemplate().update(new PreparedStatementCreator()
		{
			public PreparedStatement createPreparedStatement(
					Connection connection) throws SQLException
			{
				PreparedStatement ps = connection.prepareStatement(
						INSERT_SQL, new String[] { "id" });
				ps.setString(1, "Rob");
				ps.setInt(2, 12);
				ps.setInt(3, 9090);
				return ps;
			}
		}, keyHolder);

		System.out.println(
				"Auto generated Key is = " + keyHolder.getKey());
	}

}
